package com.imandroid.simplefoursquare.util

const val CLIENT_ID = "VFE1CLQDAO25MOTVQD34PUTMQLR0KYJLU0NS1IVUA24UKA0E"
const val CLIENT_SECRET = "F5C3NG3IDXKWFX1RULJFNC4RQWFJX1VHVWUTGW5YWN54314Z"

//const val CLIENT_ID = "SUZQUWCFZVRZN5S0B1QHCCFXR1YPALOBKGWWNVXY2K0OKYFX"
//const val CLIENT_SECRET = "PN101CPQRRHCSQAJKWQLRITTFLN0U3DR3CHPHSKQ5MWYL51N"

//const val CLIENT_ID = "SKD1GIOOQJU3XN5INXFUP0TZT3ULPDV2HZFEA1W5F0P2PGTS"
//const val CLIENT_SECRET = "4UH0ZX1E2O5PQ25XQPF4DURPPXH2MT5KSHHFFLGU3EAZPLID"

const val VERSION_API = "20200210"
const val SAMPLE_LAT_LNG = "31.3119,48.6617"
const val BROADCAST_UPDATE_EXPLORE_LIST = "UPDATE_EXPLORE_LIST"
const val BROADCAST_UPDATE_DISTANCE = "BROADCAST_UPDATE_DISTANCE"
const val KEY_RECYCLER_STATE = "KEY_RECYCLER_STATE"
const val BROADCAST_STOP_SERVICE = "BROADCAST_STOP_SERVICE"
const val LATLONG = "LATLONG"
const val IS_NEED_CLEAR = "IS_NEED_CLEAR"
const val DISTANCE = "DISTANCE"
const val SH_LAST_LAT_LNG = "LAST_LAT_LNG"
const val SH_CITY_NAME = "SH_CITY_NAME"
const val SH_STATE_NAME = "SH_STATE_NAME"
const val SH_COUNTRY_NAME = "SH_COUNTRY_NAME"
const val SH_TOTAL_PAGE = "SH_TOTAL_PAGE"
const val SH_IS_LAST_PAGE = "SH_IS_LAST_PAGE"
const val SH_DISTANCE = "SH_DISTANCE"

//const val SH_TOTAL_PAGE = "SH_TOTAL_PAGE"

const val QUALITY_ORIGINAL = "original"
const val QUALITY_36 = "36x36"
const val QUALITY_100 = "100x100"
const val QUALITY_300 = "300x300"
const val QUALITY_500 = "500x500"

const val LOCATION_PERMISSIONS_REQUEST = 546